---
- hosts: cluster
  become: yes
  become_method: sudo
  gather_facts: yes

  tasks:
    # Stop and disable the lightauth service 
    - name: Stop and disable the lightauth service
      service: name=lightauth2 enabled=no state=stopped

    # Remove service definition file
    - name: Remove lightauth service
      file: path=/etc/systemd/system/lightauths.service state=absent

    # Remove lightauth application
    - name: Remove lightauth application
      file: path=/usr/bin/lightauth2 state=absent



